### ISSUE TITLE
Share namespaces between boxes

### ISSUE THREAD

**Issue by seirl** [cms-dev/isolate#15]
Currently there is no way to share namespaces between the different boxes.
As I would need this feature to sandbox processes that needs to communicate between them using sockets, I want to add a feature which would allow you to specify that you want a box to share the same network namespace than another one, so that isolate could `setns(2)` just after the box is created.
As I'm not really familiar with this project, I'd like to know what would be the best way to implement this functionality in the current code.

Thanks!

**Comment by giomasce** [comment]
I am not particularly familiar with the code as well (it was mostly written by other people than current CMS developers) and I do not have time at the moment to think specifically on this request. If you want to design an implementation and submit it, I will be happy to look at it when I will have time, but I cannot make any promises on when this will happen.

**Comment by gollux** [comment]
You can use --share-net in the current upstream version.

**Comment by giomasce** [comment]
Given that the feature was implemented, I am closing the issue.
