### ISSUE TITLE
`make install` rule

### ISSUE THREAD

**Issue by seirl** [cms-dev/isolate#16]
It would be really convenient to have a `make install` rule that installs the manpage and the binary in the prefix. That would allow for easier packaging of `isolate`.

**Comment by giomasce** [comment]
At the moment isolate is mostly meant to be used along with CMS, so it is installed by CMS scripts. So far we feel no need to provide it with another installer. However if you want to write one I will be happy to include it.

**Comment by seirl** [comment]
See https://github.com/cms-dev/isolate/pull/17

**Comment by seirl** [comment]
Ping?
I don't want to be too insistent here, but given the simplicity of the commit I just wanted to make sure if didn't get off your radar :-).
For the record, having this patch upstream would allow me to package isolate for the archlinux user repository conforming to their guidelines, and it would really ease our deployments.

Thanks!

**Comment by gollux** [comment]
> Ping?

Actually, this repository is not upstream :)

Until two days ago, the upstream was the Moe Contest System repository,
now I am in the process of moving it to Github. See https://github.com/ioi/isolate
and stay tuned, "make install" will appear there soon.

**Comment by gollux** [comment]
It just happened. BTW, when you make the archlinux package, I will be interested in a pointer, so that I can add it to the documentation.

**Comment by seirl** [comment]
Perfect, thanks!
The package is available here: https://aur.archlinux.org/packages/isolate-git/

Archlinux users can install it using the yaourt or pacaur utilities:

    yaourt -S isolate-git

or:

    pacaur -S isolate-git

**Comment by giomasce** [comment]
This has been solved upstream.
