### ISSUE TITLE
Which one is the actual project upstream?

### ISSUE THREAD

**Issue by seirl** [cms-dev/isolate#24]
Is it https://github.com/cms-dev/isolate or https://github.com/ioi/isolate? Where should we submit patches and issues? Shouldn't the other repository disable issue creation and redirect to the other projects?

**Comment by gollux** [comment]
ioi/isolate is the upstream repository, please submit patches and issues there, except possibly for issues related to the interaction between CMS and Isolate.

**Comment by stefano-maggiolo** [comment]
Confirmed, we recently moved to tracking ioi/isolate. We should probably change the readme to reflect this.

**Comment by giomasce** [comment]
The README already appears to point to ioi/isolate. cms-dev/isolate is meant to be a fork with just the small modifications required to integrate isolate with CMS. However issues remain active on cms-dev/isolate, becuase there might be the need to track something related to the CMS fork of isolate. On the other hand, most of isolate issues open at the moment on cms-dev/isolate were just submitted before ioi/isolate existed. They should be migrated (if applicable) or closed (if they're not relevant anymore), but I'm not sure of when I will have time to do it.
