### ISSUE TITLE
Status of this repo?

### ISSUE THREAD

**Issue by xelez** [cms-dev/isolate#27]
It took me awhile to find out that cms/isolate submodule links to https://github.com/ioi/isolate and not this repository.

So, whats the status of the current repo? Is it outdated? I think some clarification in the description and readme is necessary.

**Comment by stefano-maggiolo** [comment]
Oops, apologies - yes, this is not used anymore, and cms-dev/cms points to ioi/isolate (which is the authoritative version, not only for CMS). I'll update the readme.
