### ISSUE TITLE
isolate fails to set stack limit to infinity

### ISSUE THREAD

**Issue by pamaury** [cms-dev/isolate#28]
I tried to run isolate on a very recent linux kernel (4.14.0-2-amd64) and for some reason isolate fails to set the stack limit. The problem is not very specific to isolate but rather with that line of code:

> RLIM(STACK, (stack_limit ? (rlim_t)stack_limit * 1024 : RLIM_INFINITY));

Note that it happens *even* if isolate is called without enforcing *any* memory limit. For example this produce the problem on my computer:

> /usr/local/bin/isolate --init --box-id=42
> /usr/local/bin/isolate --run --box-id=42 -- ./hello
> /usr/local/bin/isolate --cleanup --box-id=42

It seems that on recent kernels, trying to call setrlimit for the STACK with infinity fails with "Operation not permitted". I have not been able to find out why this is the case, but clearly this is a change of behavior because on an older 3.16 kernel, it works flawlessly.

**Comment by gollux** [comment]
Could you please try the version of isolate in mj-rlimit branch?

**Comment by pamaury** [comment]
The version of mj-rlimit branch works perfectly :) Should I close the issue or leave it until that branch is merged ?

**Comment by gollux** [comment]
> The version of mj-rlimit branch works perfectly :)

Thanks for the test!  I will merge the branch soon, so feel free to close this
issue now.
